### ISSUE TITLE
Question re ArchiveViewProvider Namespace

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-versioned-admin#69]
I don't trust my PSR-fu but should `ArchiveViewProvider` be in the `SilverStripe\VersionedAdmin\Interfaces` namespace rather than `SilverStripe\VersionedAdmin`? given that it lives in the `Interfaces` folder?

I ran into a strange phpunit error saying it couldn't find this class recently and I wondered if that was causing problems

**Comment by ScopeyNZ** [comment]
Yep that's right - PSR-4 dictates that it should be. Technically we're not PSR-4 yet but this could be why you have issues with tests, sometimes we rely on the composer autoloader rather than the manifest builder to load classes.

Would you like to raise a quick PR?

**Comment by blueo** [comment]
done: https://github.com/silverstripe/silverstripe-versioned-admin/pull/70

**Comment by robbieaverill** [comment]
While this is a major change, we can still get it into 1.1.x-dev before it's stabilised (and we should!)

**Comment by robbieaverill** [comment]
Done in #70
